In [48]:
import numpy as np
import matplotlib.pyplot as plt
import xarray as xr
import cdflib

In [49]:
from cdasws import CdasWs

cdas = CdasWs()

In [52]:
data_source = "AC_H2_MFI"  # OMNIWeb Combined, definitive data source, hourly
time_start = "2020-01-01T00:00:00.000Z"  # Start of analysis
time_end = "2022-01-01T00:00:00.000Z"  # End of analysis

In [51]:
# Downloads dataset using cdasws
def get_dataset(source, variables, start, end):
    res = cdas.get_data(dataset=source, variables=variables, time0=start, time1=end)
    status = res[0]
    data = res[1]

    if status["http"]["status_code"] != 200:
        print("ERR: Download from dataset server failed!")
        return

    return data

In [53]:
ds = get_dataset(data_source, ["BGSM"], time_start, time_end)

/Users/cat/anaconda3/envs/mrec/lib/python3.11/site-packages/cdflib/xarray/cdf_to_xarray.py:619: UserWarning: Converting non-nanosecond precision datetime values to nanosecond precision. This behavior can eventually be relaxed in xarray, as it is an artifact from pandas which is now beginning to support non-nanosecond precision values. This warning is caused by passing non-nanosecond np.datetime64 or np.timedelta64 values to the DataArray or Variable constructor; it can be silenced by converting the values to nanosecond precision ahead of time.
  created_vars[var_name] = xr.Variable(var_dims, var_data, attrs=var_atts)  # type: ignore[no-untyped-call]


In [54]:
ds

<xarray.Dataset>
Dimensions:    (Epoch: 17545, cartesian: 3)
Coordinates:
  * Epoch      (Epoch) datetime64[ns] 2020-01-01 ... 2022-01-01
  * cartesian  (cartesian) <U11 'x_component' 'y_component' 'z_component'
    metavar0   (cartesian) <U8 'Bx (GSM)' 'By (GSM)' 'Bz (GSM)'
Data variables:
    BGSM       (Epoch, cartesian) float32 0.359 0.075 -0.04 ... 4.552 -1.024
Attributes: (12/29)
    TITLE:                       ['ACE> Magnetometer Parameters']
    Project:                     ['ACE>Advanced Composition Explorer', 'ISTP>...
    Discipline:                  ['Space Physics>Interplanetary Studies']
    Source_name:                 ['AC>Advanced Composition Explorer']
    Data_type:                   ['H2>1-Hr Level 2 Data']
    Descriptor:                  ['MAG>ACE Magnetic Field Instrument']
    ...                          ...
    WEB_SITE:                    ['http://www.srl.caltech.edu/ACE/']
    ACKNOWLEDGEMENT:             ['Please acknowledge the Principal', 'Invest...
    RULES_OF_USE:                ['See the rules of use available from the AC...
    ALT_LOGICAL_SOURCE:          ['ACE_MAG_Solar-Wind-Magnetic-Field-Level2-H...
    SPASE_DATASETRESOURCEID:     ['spase://NASA/NumericalData/ACE/MAG/L2/PT1H']
    CDAWEB_PARENTS:              ['ac_h2_mfi_00000000_v01', 'ac_h2_mfi_202001...

In [55]:
ds = ds["BGSM"]

In [56]:
ds

<xarray.DataArray 'BGSM' (Epoch: 17545, cartesian: 3)>
array([[ 0.359,  0.075, -0.04 ],
       [ 1.673, -1.312,  0.208],
       [ 3.296, -2.823,  0.773],
       ...,
       [-5.112,  2.987, -0.944],
       [-5.852,  2.925, -3.755],
       [-5.812,  4.552, -1.024]], dtype=float32)
Coordinates:
  * Epoch      (Epoch) datetime64[ns] 2020-01-01 ... 2022-01-01
  * cartesian  (cartesian) <U11 'x_component' 'y_component' 'z_component'
    metavar0   (cartesian) <U8 'Bx (GSM)' 'By (GSM)' 'Bz (GSM)'
Attributes: (12/19)
    FIELDNAM:       Mag field vector, GSM coord
    VALIDMIN:       [-65534. -65534. -65534.]
    VALIDMAX:       [65534. 65534. 65534.]
    SCALEMIN:       [-25. -25. -25.]
    SCALEMAX:       [25. 25. 25.]
    UNITS:          nT
    ...             ...
    CATDESC:        Magnetic field vector in GSM coordinates (1 hr)
    DISPLAY_TYPE:   time_series
    SCALETYP:       LINEAR
    DIM_SIZES:      3
    standard_name:  Mag field vector, GSM coord
    units:          nT

In [57]:
ds.to_dataset()

<xarray.Dataset>
Dimensions:    (Epoch: 17545, cartesian: 3)
Coordinates:
  * Epoch      (Epoch) datetime64[ns] 2020-01-01 ... 2022-01-01
  * cartesian  (cartesian) <U11 'x_component' 'y_component' 'z_component'
    metavar0   (cartesian) <U8 'Bx (GSM)' 'By (GSM)' 'Bz (GSM)'
Data variables:
    BGSM       (Epoch, cartesian) float32 0.359 0.075 -0.04 ... 4.552 -1.024

In [58]:
ds

<xarray.DataArray 'BGSM' (Epoch: 17545, cartesian: 3)>
array([[ 0.359,  0.075, -0.04 ],
       [ 1.673, -1.312,  0.208],
       [ 3.296, -2.823,  0.773],
       ...,
       [-5.112,  2.987, -0.944],
       [-5.852,  2.925, -3.755],
       [-5.812,  4.552, -1.024]], dtype=float32)
Coordinates:
  * Epoch      (Epoch) datetime64[ns] 2020-01-01 ... 2022-01-01
  * cartesian  (cartesian) <U11 'x_component' 'y_component' 'z_component'
    metavar0   (cartesian) <U8 'Bx (GSM)' 'By (GSM)' 'Bz (GSM)'
Attributes: (12/19)
    FIELDNAM:       Mag field vector, GSM coord
    VALIDMIN:       [-65534. -65534. -65534.]
    VALIDMAX:       [65534. 65534. 65534.]
    SCALEMIN:       [-25. -25. -25.]
    SCALEMAX:       [25. 25. 25.]
    UNITS:          nT
    ...             ...
    CATDESC:        Magnetic field vector in GSM coordinates (1 hr)
    DISPLAY_TYPE:   time_series
    SCALETYP:       LINEAR
    DIM_SIZES:      3
    standard_name:  Mag field vector, GSM coord
    units:          nT

In [59]:
ds[:, 1]

<xarray.DataArray 'BGSM' (Epoch: 17545)>
array([ 0.075, -1.312, -2.823, ...,  2.987,  2.925,  4.552], dtype=float32)
Coordinates:
  * Epoch      (Epoch) datetime64[ns] 2020-01-01 ... 2022-01-01
    cartesian  <U11 'y_component'
    metavar0   <U8 'By (GSM)'
Attributes: (12/19)
    FIELDNAM:       Mag field vector, GSM coord
    VALIDMIN:       [-65534. -65534. -65534.]
    VALIDMAX:       [65534. 65534. 65534.]
    SCALEMIN:       [-25. -25. -25.]
    SCALEMAX:       [25. 25. 25.]
    UNITS:          nT
    ...             ...
    CATDESC:        Magnetic field vector in GSM coordinates (1 hr)
    DISPLAY_TYPE:   time_series
    SCALETYP:       LINEAR
    DIM_SIZES:      3
    standard_name:  Mag field vector, GSM coord
    units:          nT

In [60]:
ds.to_dataframe()

metavar0   BGSM
Epoch               cartesian                   
2020-01-01 00:00:00 x_component  Bx (GSM)  0.359
                    y_component  By (GSM)  0.075
                    z_component  Bz (GSM) -0.040
2020-01-01 01:00:00 x_component  Bx (GSM)  1.673
                    y_component  By (GSM) -1.312
...                                   ...    ...
2021-12-31 23:00:00 y_component  By (GSM)  2.925
                    z_component  Bz (GSM) -3.755
2022-01-01 00:00:00 x_component  Bx (GSM) -5.812
                    y_component  By (GSM)  4.552
                    z_component  Bz (GSM) -1.024

[52635 rows x 2 columns]

In [61]:
ds[:, 0].to_dataframe()

cartesian  metavar0   BGSM
Epoch                                            
2020-01-01 00:00:00  x_component  Bx (GSM)  0.359
2020-01-01 01:00:00  x_component  Bx (GSM)  1.673
2020-01-01 02:00:00  x_component  Bx (GSM)  3.296
2020-01-01 03:00:00  x_component  Bx (GSM)  3.879
2020-01-01 04:00:00  x_component  Bx (GSM)  4.029
...                          ...       ...    ...
2021-12-31 20:00:00  x_component  Bx (GSM)  2.499
2021-12-31 21:00:00  x_component  Bx (GSM)  0.109
2021-12-31 22:00:00  x_component  Bx (GSM) -5.112
2021-12-31 23:00:00  x_component  Bx (GSM) -5.852
2022-01-01 00:00:00  x_component  Bx (GSM) -5.812

[17545 rows x 3 columns]

In [62]:
da_x = xr.DataArray(ds[:, 0].to_dataframe())

In [63]:
da_x

<xarray.DataArray (Epoch: 17545, dim_1: 3)>
array([['x_component', 'Bx (GSM)', 0.35899999737739563],
       ['x_component', 'Bx (GSM)', 1.6729999780654907],
       ['x_component', 'Bx (GSM)', 3.2960000038146973],
       ...,
       ['x_component', 'Bx (GSM)', -5.111999988555908],
       ['x_component', 'Bx (GSM)', -5.8520002365112305],
       ['x_component', 'Bx (GSM)', -5.811999797821045]], dtype=object)
Coordinates:
  * Epoch    (Epoch) datetime64[ns] 2020-01-01 ... 2022-01-01
  * dim_1    (dim_1) object 'cartesian' 'metavar0' 'BGSM'

In [64]:
row_x = ds[:, 0]

In [65]:
row_x

<xarray.DataArray 'BGSM' (Epoch: 17545)>
array([ 0.359,  1.673,  3.296, ..., -5.112, -5.852, -5.812], dtype=float32)
Coordinates:
  * Epoch      (Epoch) datetime64[ns] 2020-01-01 ... 2022-01-01
    cartesian  <U11 'x_component'
    metavar0   <U8 'Bx (GSM)'
Attributes: (12/19)
    FIELDNAM:       Mag field vector, GSM coord
    VALIDMIN:       [-65534. -65534. -65534.]
    VALIDMAX:       [65534. 65534. 65534.]
    SCALEMIN:       [-25. -25. -25.]
    SCALEMAX:       [25. 25. 25.]
    UNITS:          nT
    ...             ...
    CATDESC:        Magnetic field vector in GSM coordinates (1 hr)
    DISPLAY_TYPE:   time_series
    SCALETYP:       LINEAR
    DIM_SIZES:      3
    standard_name:  Mag field vector, GSM coord
    units:          nT

In [66]:
row_x.to_dataframe()

cartesian  metavar0   BGSM
Epoch                                            
2020-01-01 00:00:00  x_component  Bx (GSM)  0.359
2020-01-01 01:00:00  x_component  Bx (GSM)  1.673
2020-01-01 02:00:00  x_component  Bx (GSM)  3.296
2020-01-01 03:00:00  x_component  Bx (GSM)  3.879
2020-01-01 04:00:00  x_component  Bx (GSM)  4.029
...                          ...       ...    ...
2021-12-31 20:00:00  x_component  Bx (GSM)  2.499
2021-12-31 21:00:00  x_component  Bx (GSM)  0.109
2021-12-31 22:00:00  x_component  Bx (GSM) -5.112
2021-12-31 23:00:00  x_component  Bx (GSM) -5.852
2022-01-01 00:00:00  x_component  Bx (GSM) -5.812

[17545 rows x 3 columns]

In [67]:
row_x = row_x.to_dataframe()

In [68]:
row_x.axes

[DatetimeIndex(['2020-01-01 00:00:00', '2020-01-01 01:00:00',
                '2020-01-01 02:00:00', '2020-01-01 03:00:00',
                '2020-01-01 04:00:00', '2020-01-01 05:00:00',
                '2020-01-01 06:00:00', '2020-01-01 07:00:00',
                '2020-01-01 08:00:00', '2020-01-01 09:00:00',
                ...
                '2021-12-31 15:00:00', '2021-12-31 16:00:00',
                '2021-12-31 17:00:00', '2021-12-31 18:00:00',
                '2021-12-31 19:00:00', '2021-12-31 20:00:00',
                '2021-12-31 21:00:00', '2021-12-31 22:00:00',
                '2021-12-31 23:00:00', '2022-01-01 00:00:00'],
               dtype='datetime64[ns]', name='Epoch', length=17545, freq=None),
 Index(['cartesian', 'metavar0', 'BGSM'], dtype='object')]

In [69]:
row_x.drop('cartesian')

KeyError: "['cartesian'] not found in axis"

In [71]:
import pandas as pd

data = {'A': [1, 2, 3], 'B': [4, 5, 6], 'C': [7, 8, 9]}
df = pd.DataFrame(data)


In [72]:
df

A  B  C
0  1  4  7
1  2  5  8
2  3  6  9

In [73]:
row_x

cartesian  metavar0   BGSM
Epoch                                            
2020-01-01 00:00:00  x_component  Bx (GSM)  0.359
2020-01-01 01:00:00  x_component  Bx (GSM)  1.673
2020-01-01 02:00:00  x_component  Bx (GSM)  3.296
2020-01-01 03:00:00  x_component  Bx (GSM)  3.879
2020-01-01 04:00:00  x_component  Bx (GSM)  4.029
...                          ...       ...    ...
2021-12-31 20:00:00  x_component  Bx (GSM)  2.499
2021-12-31 21:00:00  x_component  Bx (GSM)  0.109
2021-12-31 22:00:00  x_component  Bx (GSM) -5.112
2021-12-31 23:00:00  x_component  Bx (GSM) -5.852
2022-01-01 00:00:00  x_component  Bx (GSM) -5.812

[17545 rows x 3 columns]

In [75]:
row_x.drop('metavar0', axis=1)

cartesian   BGSM
Epoch                                  
2020-01-01 00:00:00  x_component  0.359
2020-01-01 01:00:00  x_component  1.673
2020-01-01 02:00:00  x_component  3.296
2020-01-01 03:00:00  x_component  3.879
2020-01-01 04:00:00  x_component  4.029
...                          ...    ...
2021-12-31 20:00:00  x_component  2.499
2021-12-31 21:00:00  x_component  0.109
2021-12-31 22:00:00  x_component -5.112
2021-12-31 23:00:00  x_component -5.852
2022-01-01 00:00:00  x_component -5.812

[17545 rows x 2 columns]

In [77]:
row_x = row_x.drop('cartesian', axis=1)

In [78]:
row_x = row_x.drop('metavar0', axis=1)

In [79]:
row_x

BGSM
Epoch                     
2020-01-01 00:00:00  0.359
2020-01-01 01:00:00  1.673
2020-01-01 02:00:00  3.296
2020-01-01 03:00:00  3.879
2020-01-01 04:00:00  4.029
...                    ...
2021-12-31 20:00:00  2.499
2021-12-31 21:00:00  0.109
2021-12-31 22:00:00 -5.112
2021-12-31 23:00:00 -5.852
2022-01-01 00:00:00 -5.812

[17545 rows x 1 columns]

In [83]:
da_x = xr.DataArray(row_x['BGSM'], dims='Epoch', coords={'Epoch': row_x.index})

In [84]:
da_x

<xarray.DataArray 'BGSM' (Epoch: 17545)>
array([ 0.359,  1.673,  3.296, ..., -5.112, -5.852, -5.812], dtype=float32)
Coordinates:
  * Epoch    (Epoch) datetime64[ns] 2020-01-01 ... 2022-01-01

In [85]:
ds = xr.Dataset({'x': da_x})

In [86]:
ds

<xarray.Dataset>
Dimensions:  (Epoch: 17545)
Coordinates:
  * Epoch    (Epoch) datetime64[ns] 2020-01-01 ... 2022-01-01
Data variables:
    x        (Epoch) float32 0.359 1.673 3.296 3.879 ... -5.112 -5.852 -5.812